### PR TITLE
Pr/ftdi tools

### PR DESCRIPTION
**Pull request by LudwigKnuepfer**

### CODE REVIEW

**Comment by jnohlgard** [comment]
This does not work on FT2232H devices for me.

**Comment by jnohlgard** [comment]
(it finds no tty devices)

**Comment by LudwigKnuepfer** [comment]
Huh, could you paste the directory layout?

**Comment by jnohlgard** [comment]
This is a machine with two programmers connected on different USB ports and using USB hubs:

```
# uname -a
Linux hostname 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Old list-ttys.sh:

```
/sys/bus/usb/devices/2-6.2.1.1: Eistec AB Mulle Programmer v0.70 serial: '310', tty(s): ttyUSB0, 
/sys/bus/usb/devices/6-1: Eistec AB Mulle Programmer v0.60 serial: '147', tty(s): ttyUSB1, ttyUSB2, 
```

```
# find /sys/bus/usb/devices/[0-9]*/ -maxdepth 4 -name tty -follow -print 2> /dev/null
/sys/bus/usb/devices/2-6.2.1/2-6.2.1.1/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/2-6.2.1.1/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/2-6.2.1.1:1.0/driver/6-1:1.0/ttyUSB1/tty
/sys/bus/usb/devices/2-6.2.1.1:1.0/driver/6-1:1.1/ttyUSB2/tty
/sys/bus/usb/devices/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/2-6.2.1.1:1.0/ttyUSB0/driver/ttyUSB1/tty
/sys/bus/usb/devices/2-6.2.1.1:1.0/ttyUSB0/driver/ttyUSB2/tty
/sys/bus/usb/devices/6-1/6-1:1.0/ttyUSB1/tty
/sys/bus/usb/devices/6-1/6-1:1.1/ttyUSB2/tty
/sys/bus/usb/devices/6-1:1.0/driver/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/6-1:1.0/driver/6-1:1.1/ttyUSB2/tty
/sys/bus/usb/devices/6-1:1.0/ttyUSB1/tty
/sys/bus/usb/devices/6-1:1.0/ttyUSB1/driver/ttyUSB0/tty
/sys/bus/usb/devices/6-1:1.0/ttyUSB1/driver/ttyUSB2/tty
/sys/bus/usb/devices/6-1:1.1/driver/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/6-1:1.1/driver/6-1:1.0/ttyUSB1/tty
/sys/bus/usb/devices/6-1:1.1/ttyUSB2/tty
/sys/bus/usb/devices/6-1:1.1/ttyUSB2/driver/ttyUSB0/tty
/sys/bus/usb/devices/6-1:1.1/ttyUSB2/driver/ttyUSB1/tty
```

```
# find /sys/bus/usb/devices/[0-9]*/ -maxdepth 3 -name tty -follow -print 2> /dev/null
/sys/bus/usb/devices/2-6.2.1.1/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/2-6.2.1.1:1.0/ttyUSB0/tty
/sys/bus/usb/devices/6-1/6-1:1.0/ttyUSB1/tty
/sys/bus/usb/devices/6-1/6-1:1.1/ttyUSB2/tty
/sys/bus/usb/devices/6-1:1.0/ttyUSB1/tty
/sys/bus/usb/devices/6-1:1.1/ttyUSB2/tty
```

I can send you a full tree dump, but it is too long to paste here (350 kB).

**Comment by LudwigKnuepfer** [comment]
OK, so how about this?
`find /sys/bus/usb/devices/ -mindepth 3 -maxdepth 3 -name tty -follow -printf '%h\n' 2>/dev/null`

**Comment by LudwigKnuepfer** [comment]
@gebart does the above `find` work for you?

**Comment by LudwigKnuepfer** [comment]
@gebart ping

**Comment by jnohlgard** [comment]
Sorry for the delay, it seems to work for me:

```
% find /sys/bus/usb/devices/ -mindepth 3 -maxdepth 3 -name tty -follow -printf '%h\n' 2>/dev/null
/sys/bus/usb/devices/2-6.2.1.1:1.0/ttyUSB0
/sys/bus/usb/devices/6-1:1.0/ttyUSB1
/sys/bus/usb/devices/6-1:1.1/ttyUSB2
```

**Comment by LudwigKnuepfer** [comment]
```
$ ./dist/tools/usb-serial/list-ttys.sh
/sys/bus/usb/devices/1-1.1:1.0:   serial: '', tty(s): ttyUSB0, 
/sys/bus/usb/devices/2-1.6.4.1: STMicroelectronics STM32 STLink serial: '0669FF484951775087075220', tty(s): ttyACM2, 
/sys/bus/usb/devices/2-1.6.4.3: Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800001519', tty(s): ttyACM0, 
/sys/bus/usb/devices/2-1.6.4.4: Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800001237', tty(s): ttyACM1, 
```

**Comment by LudwigKnuepfer** [comment]
Your original PR:

```
$ ./dist/tools/usb-serial/list-ttys.sh
/sys/bus/usb/devices/1-1.1: FU Berlin MSB430A serial: 'ARWBN7L8', tty(s): ttyUSB0, 
/sys/bus/usb/devices/2-1.6.4:  USB 2.0 Hub serial: '', tty(s): ttyACM2, ttyACM0, ttyACM1, 
/sys/bus/usb/devices/2-1.6.4.1: STMicroelectronics STM32 STLink serial: '0669FF484951775087075220', tty(s): ttyACM2, 
/sys/bus/usb/devices/2-1.6.4.3: Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800001519', tty(s): ttyACM0, 
/sys/bus/usb/devices/2-1.6.4.4: Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800001237', tty(s): ttyACM1, 
``
```

**Comment by LudwigKnuepfer** [comment]
I'll look into it later today in case you didn't in the meantime.

**Comment by LudwigKnuepfer** [comment]
For reference:

```
$ ls /sys/bus/usb/devices/1-1.1/1-1.1:1.0/ttyUSB0/tty
ttyUSB0
```

**Comment by LudwigKnuepfer** [comment]
```
$ ./dist/tools/usb-serial/list-ttys.sh
/sys/bus/usb/devices/2-1.6.4.1: STMicroelectronics STM32 STLink serial: '0669FF484951775087075220', tty(s): ttyACM1
/sys/bus/usb/devices/2-1.6.4.3: Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800001519', tty(s): ttyACM0
/sys/bus/usb/devices/2-1.6.4.4: Atmel Corp. EDBG CMSIS-DAP serial: 'ATML2127031800001237', tty(s): ttyACM2
/sys/bus/usb/devices/2-1.6.2: FU Berlin MSB430A serial: 'ARWBN7L8', tty(s): ttyUSB0
```

**Comment by LudwigKnuepfer** [comment]
@gebart that should do it.

**Comment by jnohlgard** [comment]
Small nitpick: Can you make it merge lines with the same device to show all ttys on the same line?

```
% ./list-ttys.sh 
/sys/bus/usb/devices/6-1: Eistec AB Mulle Programmer v0.60 serial: '147', tty(s): ttyUSB1
/sys/bus/usb/devices/6-1: Eistec AB Mulle Programmer v0.60 serial: '147', tty(s): ttyUSB2
/sys/bus/usb/devices/2-6.2.1.1: Eistec AB Mulle Programmer v0.70 serial: '310', tty(s): ttyUSB0
```

**Comment by LudwigKnuepfer** [comment]
Probably not for the next two weeks.

**Comment by LudwigKnuepfer** [comment]
@gebart please give it a try

**Comment by jnohlgard** [comment]
Almost, only there is some garbage in the output of the `ls` command when passed more than one directory:

```
/sys/bus/usb/devices/1-1: Eistec AB Mulle Programmer v0.70 serial: '312', tty(s): /sys/bus/usb/devices/1-1/1-1:1.0/ttyUSB0/tty:
ttyUSB0

/sys/bus/usb/devices/1-1/1-1:1.1/ttyUSB1/tty:
ttyUSB1
/sys/bus/usb/devices/1-2: FTDI TTL232R-3V3 serial: 'FTFAKJQO', tty(s): ttyUSB2
```

it works with the following ttys= line:

``` sh
    ttys=$(for t in ${tty}; do echo ${t}/* | xargs basename -a | tr "\n" ','; done | sed -e 's/,$//' -e 's/,/, /g' 2>/dev/null)
```

Output:

```
/sys/bus/usb/devices/1-1: Eistec AB Mulle Programmer v0.70 serial: '312', tty(s): ttyUSB0, ttyUSB1
/sys/bus/usb/devices/1-2: FTDI TTL232R-3V3 serial: 'FTFAKJQO', tty(s): ttyUSB2
```

**Pull request merged**
