### PR TITLE
mtd spi nor erase improvements

### PR DESCRIPTION
**Pull request by vincent-d**
Hi,

I rebased it on top of the mtd PR and improved the erase with 4Kio sectors.
@gebart  please review and let me know.

### CODE REVIEW

**Comment by jnohlgard** [comment]
Some good improvements!

maybe we should change the names of the functions for erase (`block_erase`, `sector_erase`) to `sector_erase_4k`,  `sector_erase_32k`,  `sector_erase_64k` etc?
I noticed that another NOR flash (n25p) that I will use in an upcoming project supports 64k, 32k and 4k erases.

I'm not sure I agree with adding the macro `MTD_SPI_NOR_DESC` because I think it makes the code less readable since there are so many positional arguments.

What is the purpose of the enum `SPI_NOR_F_SECT_4K`? It seems like it is not used anywhere.

**Comment by vincent-d** [comment]
> maybe we should change the names of the functions for erase (block_erase, sector_erase) to sector_erase_4k, sector_erase_32k, sector_erase_64k etc?
> I noticed that another NOR flash (n25p) that I will use in an upcoming project supports 64k, 32k and 4k erases.

Why not, I think the mx25 we use also support erase by 4k, 32k and 64k, but I'm not 100% sure, I'll check that.

> I'm not sure I agree with adding the macro MTD_SPI_NOR_DESC because I think it makes the code less readable since there are so many positional arguments.

Yeah, I'm not a big fan of that idea either, but I'd really like to find a way to easily use a "supported" flash without having to write a lot of struct initialization somewhere ine the board config. So far, I don't have any better idea...

> What is the purpose of the enum SPI_NOR_F_SECT_4K? It seems like it is not used anywhere.

I first went through the MTD SPI NOR Linux code which seems to use such a flag, then I realized that it was not so useful in our case, I think we can use the size of the sector directly.

**Comment by vincent-d** [comment]
4k, 32k and 64k erase are supported.

`mtd->sector_size` is the smallest erasable unit. The `flag` member is used to know if 4k or 32k erase are supported.

**Comment by jnohlgard** [comment]
Closing this since we moved to another PR upstream.

**Pull request closed without merging**
